name: 'Deploy Helix World'
description: 'Uploads a Helix automatically'
inputs:
  access_token:
    description: 'Access token for authentication. Can be generated at Account -> Settings'
    required: true
  world_name:
    description: 'Name of the world to upload. Make sure you already have this world created. If not set a world will be created'
    required: false
    default: ''
  packages_path:
    description: 'Path to the packages directory. Defaults to the current directory'
    required: false
  private_ssh_key:
    description: 'Private SSH key for authentication in github'
    required: false
  master_endpoint:
    description: 'Defaults to https://api.helixgame.com/v1'
    required: false
    default: 'https://api.helixgame.com/v1'
  ref:
    description: 'Optional git ref to checkout to'
    required: false
    default: ''

outputs:
  world_id:
    description: "World ID that was uploaded"
    value: ${{ steps.get_world_id.outputs.world_id }}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
        ref: ${{ inputs.ref }}

    - name: Update Submodules
      shell: bash
      env:
        PRIVATE_SSH_KEY: ${{ inputs.private_ssh_key }}
      run: |
        if [ -z "$PRIVATE_SSH_KEY" ]; then
          echo "Skipping private repository setup"
        else
          echo "Configuring git for private github repositories"
          eval `ssh-agent -s`
          ssh-add - <<< "$PRIVATE_SSH_KEY"
        fi
        git submodule sync
        git submodule update --init --recursive --remote

    - name: Install jq
      shell: bash
      run: sudo apt-get install -y jq


    - name: Find and delete .git and .github folders
      shell: bash
      run: |
        echo "Searching for .git and .github folders"
        find . -type d -name ".git" -exec rm -rf {} +
        find . -type d -name ".github" -exec rm -rf {} +
        echo "Folders deleted successfully!"


    - name: Zip repository
      shell: bash
      env:
        PACKAGES_PATH: ${{ inputs.packages_path || '.' }}
      run: |
        ORIGINAL_CWD=$(pwd)
        cd "$PACKAGES_PATH"
        if [ -d "Packages" ]; then
          zip -r main.zip Packages
          mv main.zip "$ORIGINAL_CWD" || true
        else
          echo "Directory 'Packages' does not exist in $PACKAGES_PATH"
          exit 1
        fi

    - name: Create World 
      id: create_world
      if: ${{ inputs.world_name }} == ''
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        MASTER_ENDPOINT: ${{ inputs.master_endpoint }}
      run: |
        RANDOM_DESCRIPTION=$(head /dev/urandom | base64 | head -c 32)
        RANDOM_TITLE=$(head /dev/urandom | base64 | head -c 8)
        response=$(curl --location "${MASTER_ENDPOINT}/world" --header 'Content-Type: application/json' --header "Token: ${ACCESS_TOKEN}" --data "{\"description\": \"$RANDOM_DESCRIPTION\",\"title\": \"$RANDOM_TITLE\"}")
        echo "world_id=$(echo $response | jq -r '.payload.id')" >> $GITHUB_OUTPUT

    - name: Get World ID
      id: get_world_id
      shell: bash
      if: ${{ inputs.world_name }} != ''
      env:
        WORLD_NAME: ${{ inputs.world_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        MASTER_ENDPOINT: ${{ inputs.master_endpoint || 'https://api.helixgame.com/v1' }}
        WORLD_ID: ${{ steps.get_world_id.outputs.world_id }}
      run: |
        if [ "$WORLD_ID" != "" ]; then
          echo "World ID already set"
          echo "world_id=$WORLD_ID" >> $GITHUB_OUTPUT
          exit 0
        fi
        response=$(curl --location "${MASTER_ENDPOINT}/world/${WORLD_NAME}" --header "Token: ${ACCESS_TOKEN}")
        echo "world_id=$(echo $response | jq -r '.payload.id')" >> $GITHUB_OUTPUT

    - name: Request presigned URL
      id: presigned_url
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        WORLD_ID: ${{ steps.get_world_id.outputs.world_id }}
        MASTER_ENDPOINT: ${{ inputs.master_endpoint }}
      run: |
        response=$(curl --location "${MASTER_ENDPOINT}/world/upload/packages/${WORLD_ID}" --header "Token: ${ACCESS_TOKEN}")
        code=$(echo $response | jq -r '.code')
        message=$(echo $response | jq -r '.message')
        if [ "$code" != "0" ]; then
          if [ "$message" == "world corrupted" ]; then
            echo "Error: Make sure you've created this world on the HELIX Hub first: https://hub.helixgame.com/creations/worlds"
          else
            echo "Error: Server returned error code $code with message '$message'"
          fi
          exit 1
        fi
        echo "upload_url=$(echo $response | jq -r '.payload.upload_url')" >> $GITHUB_OUTPUT
        echo "world_url=$(echo $response | jq -r '.payload.world_url')" >> $GITHUB_OUTPUT

    - name: Upload zip file
      shell: bash
      env:
        UPLOAD_URL: ${{ steps.presigned_url.outputs.upload_url }}
      run: |
        curl --location --request PUT "${UPLOAD_URL}" \
          --header "Content-Type: application/zip" \
          --data-binary "@main.zip"

    - name: Finish upload
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        WORLD_URL: ${{ steps.presigned_url.outputs.world_url }}
        WORLD_ID: ${{ steps.get_world_id.outputs.world_id || steps.create_world.outputs.world_id }}
        MASTER_ENDPOINT: ${{ inputs.master_endpoint || 'https://api.helixgame.com/v1' }}
      run: |
        echo $WORLD_ID
        curl --location "${MASTER_ENDPOINT}/world/upload/packages/finish?url=${WORLD_URL}&world_id=${WORLD_ID}" --header "Token: ${ACCESS_TOKEN}"

